Code used to sanity-check data: plotting raw and written files, calculating various statistics

# JHD (First NCAR dataset) Plot NetCDF Raw data

### Setup

In [ ]:
import zarr
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr

import os

In [ ]:
# %matplotlib widget

In [ ]:
# raw_ncar_folder_path = '/home/idies/workspace/turb/data02_02/ncar-low-rate-fixed-dt/'
raw_ncar_folder_path = '/home/idies/workspace/turbulence-ceph-staging/ncar-jhf/lr'
save_folder_path = '/home/idies/workspace/Storage/ariel4/persistent/ncar-zarr-code/zarr_reading/visualizations/'

chunk_size=64


var = 'e'
variable = var

# timestep_range = range(5) # This will definitely crash the Kernel
timestep_nr = 0

In [ ]:
# needed for sciserver jobs
%cd /home/idies/workspace/Storage/ariel4/persistent/zarrify-across-network

In [ ]:
# for timestep_nr in timestep_range:
#     data = xr.open_dataset(raw_ncar_folder_path + "/jhd.00" + str(timestep_nr) + ".nc")


data_xr = xr.open_dataset(raw_ncar_folder_path + "/jhf." + str(timestep_nr).zfill(3) + ".nc", chunks={'nnz': chunk_size, 'nny': chunk_size, 'nnx': chunk_size})

In [ ]:
steps = range(0, data_xr['t'].shape[2], 10)

# for i, z in enumerate(z_steps):
#     print(i,z)

### Read Access Time Results

3min 45s +- 4min(!) to load Array `np.array(data[var])`

33.3s to plot using in-memory numpy array (from above)

14min 17s +- 6min for loading data using `data_xr[var][slice]` every time

Skipping the np.array loading takes wayyy too long (>1h for 7 runs atm)

<font color="red">Use `np.array(data_xr['e'].isel(nnz=z_indices, nny=slice(None), nnx=slice(None)))`!! Only 15sec!</font>

### Plotting

In [ ]:
# TODO make this into a function

z_indices = [0]
x_indices = [0]
# z_indices = [2047]
z = 0

# Change this to slice along a different axis
# slice_data = np.array(data_xr[var].isel(nnz=z_indices, nny=slice(None), nnx=slice(None)))
# Load only 512x512
# slice_data = np.array(data_xr[var].isel(nnz=z_indices, nny=slice(0, 512), nnx=slice(0, 512)))
slice_data = np.array(data_xr[var].isel(nnz=slice(0, 512), nny=slice(0, 512), nnx=z_indices))

slice_data = np.squeeze(slice_data)

In [ ]:
slice_data.shape

In [ ]:
# slice_data = slice_data[:512, :512]

In [ ]:
plt.figure(figsize=(10,10))
plt.imshow(slice_data)#, cmap='gist_gray')#, vmin=-.5, vmax=.6)

#     name = "[z,y=" +str(y) + ",x]" # y
# name = "Timestep = ", timestep_nr, ", Var = ", var, "[z=" +str(z) + ",y,x]" # z
name = "Timestep = ", timestep_nr, ", Var = ", var, "[z,y,x=" +str(z) + "]" # x

plt.title(name, fontsize=20)
plt.colorbar()

# Save figures to disk
# plt.savefig(f'visualizations/timestep_' + str(timestep_nr) + '/' + var + "/" + name + '.png')
# plt.close()

In [ ]:
# TODO make this into a function
var = 'u'

z_indices = [0]
x_indices = [0]
# z_indices = [2047]
z = 0

# Change this to slice along a different axis
# slice_data = np.array(data_xr[var].isel(nnz=z_indices, nny=slice(None), nnx=slice(None)))
# Load only 512x512
# slice_data = np.array(data_xr[var].isel(nnz=z_indices, nny=slice(0, 512), nnx=slice(0, 512)))
slice_data = np.array(data_xr[var].isel(nnz=slice(0, 512), nny=slice(0, 512), nnx=z_indices))

slice_data = np.squeeze(slice_data)


plt.figure(figsize=(10,10))
plt.imshow(slice_data)#, cmap='gist_gray')#, vmin=-.5, vmax=.6)

#     name = "[z,y=" +str(y) + ",x]" # y
# name = "Timestep = ", timestep_nr, ", Var = ", var, "[z=" +str(z) + ",y,x]" # z
name = "Timestep = ", timestep_nr, ", Var = ", var, "[z,y,x=" +str(z) + "]" # x

plt.title(name, fontsize=20)
plt.colorbar()

# Save figures to disk
# plt.savefig(f'visualizations/timestep_' + str(timestep_nr) + '/' + var + "/" + name + '.png')
# plt.close()

In [ ]:
# TODO make this into a function
var = 'v'

z_indices = [0]
x_indices = [0]
# z_indices = [2047]
z = 0

# Change this to slice along a different axis
# slice_data = np.array(data_xr[var].isel(nnz=z_indices, nny=slice(None), nnx=slice(None)))
# Load only 512x512
# slice_data = np.array(data_xr[var].isel(nnz=z_indices, nny=slice(0, 512), nnx=slice(0, 512)))
slice_data = np.array(data_xr[var].isel(nnz=slice(0, 512), nny=slice(0, 512), nnx=z_indices))

slice_data = np.squeeze(slice_data)


plt.figure(figsize=(10,10))
plt.imshow(slice_data)#, cmap='gist_gray')#, vmin=-.5, vmax=.6)

#     name = "[z,y=" +str(y) + ",x]" # y
# name = "Timestep = ", timestep_nr, ", Var = ", var, "[z=" +str(z) + ",y,x]" # z
name = "Timestep = ", timestep_nr, ", Var = ", var, "[z,y,x=" +str(z) + "]" # x

plt.title(name, fontsize=20)
plt.colorbar()

# Save figures to disk
# plt.savefig(f'visualizations/timestep_' + str(timestep_nr) + '/' + var + "/" + name + '.png')
# plt.close()

In [ ]:
# TODO make this into a function
var = 'w'

z_indices = [0]
x_indices = [0]
# z_indices = [2047]
z = 0

# Change this to slice along a different axis
# slice_data = np.array(data_xr[var].isel(nnz=z_indices, nny=slice(None), nnx=slice(None)))
# Load only 512x512
# slice_data = np.array(data_xr[var].isel(nnz=z_indices, nny=slice(0, 512), nnx=slice(0, 512)))
slice_data = np.array(data_xr[var].isel(nnz=slice(0, 512), nny=slice(0, 512), nnx=z_indices))

slice_data = np.squeeze(slice_data)


plt.figure(figsize=(10,10))
plt.imshow(slice_data)#, cmap='gist_gray')#, vmin=-.5, vmax=.6)

#     name = "[z,y=" +str(y) + ",x]" # y
# name = "Timestep = ", timestep_nr, ", Var = ", var, "[z=" +str(z) + ",y,x]" # z
name = "Timestep = ", timestep_nr, ", Var = ", var, "[z,y,x=" +str(z) + "]" # x

plt.title(name, fontsize=20)
plt.colorbar()

# Save figures to disk
# plt.savefig(f'visualizations/timestep_' + str(timestep_nr) + '/' + var + "/" + name + '.png')
# plt.close()

In [ ]:
# TODO make this into a function
var = 't'

z_indices = [0]
x_indices = [0]
# z_indices = [2047]
z = 0

# Change this to slice along a different axis
# slice_data = np.array(data_xr[var].isel(nnz=z_indices, nny=slice(None), nnx=slice(None)))
# Load only 512x512
# slice_data = np.array(data_xr[var].isel(nnz=z_indices, nny=slice(0, 512), nnx=slice(0, 512)))
slice_data = np.array(data_xr[var].isel(nnz=slice(0, 512), nny=slice(0, 512), nnx=z_indices))

slice_data = np.squeeze(slice_data)


plt.figure(figsize=(10,10))
plt.imshow(slice_data)#, cmap='gist_gray')#, vmin=-.5, vmax=.6)

#     name = "[z,y=" +str(y) + ",x]" # y
# name = "Timestep = ", timestep_nr, ", Var = ", var, "[z=" +str(z) + ",y,x]" # z
name = "Timestep = ", timestep_nr, ", Var = ", var, "[z,y,x=" +str(z) + "]" # x

plt.title(name, fontsize=20)
plt.colorbar()

# Save figures to disk
# plt.savefig(f'visualizations/timestep_' + str(timestep_nr) + '/' + var + "/" + name + '.png')
# plt.close()

# Visually Verify Newer NCAR StSABL (jhf)

<font color='cyan'>

## Remember, index is nnz-nny-nnx. first dim is Z
    
</font>

## Plot Zarr-Written data

### High-Rate

In [30]:
stored_jhf_hr_path = "/home/idies/workspace/turbulence-ceph-staging/sciserver-turbulence/stsabl2048high/stsabl2048high.zarr"
raw_jhf_hr_0_path = "/home/idies/workspace/turbulence-ceph-staging/ncar-jhf/hr/jhf.000.nc"
raw_jhf_hr_1_path = "/home/idies/workspace/turbulence-ceph-staging/ncar-jhf/hr/jhf.001.nc"
raw_jhf_hr_104_path = "/home/idies/workspace/turbulence-ceph-staging/ncar-jhf/hr/jhf.104.nc"

In [23]:
import zarr
import xarray as xr
import numpy as np

jhf_hr_zarr = zarr.open(stored_jhf_hr_path)
jhf_hr_netcdf_t0 = xr.open_dataset(raw_jhf_hr_0_path)
jhf_hr_netcdf_t1 = xr.open_dataset(raw_jhf_hr_1_path)
jhf_hr_netcdf_t104 = xr.open_dataset(raw_jhf_hr_104_path)

#### `zarr.info`

In [20]:
jhf_hr_zarr['energy'].info

Name               : /energy
Type               : zarr.core.Array
Data type          : float32
Shape              : (105, 2048, 2048, 2048, 1)
Chunk shape        : (1, 64, 64, 64, 1)
Order              : C
Read-only          : False
Compressor         : None
Store type         : zarr.storage.DirectoryStore
No. bytes          : 3607772528640 (3.3T)
No. bytes stored   : 329
Storage ratio      : 10965873947.2
Chunks initialized : 5/3440640

In [12]:
jhf_hr_zarr['velocity'].info

Name               : /velocity
Type               : zarr.core.Array
Data type          : float32
Shape              : (105, 2048, 2048, 2048, 3)
Chunk shape        : (1, 64, 64, 64, 3)
Order              : C
Read-only          : False
Compressor         : None
Store type         : zarr.storage.DirectoryStore
No. bytes          : 10823317585920 (9.8T)
No. bytes stored   : 329
Storage ratio      : 32897621841.7
Chunks initialized : 20/3440640

In [21]:
jhf_hr_zarr.info

Name        : /
Type        : zarr.hierarchy.Group
Read-only   : False
Store type  : zarr.storage.DirectoryStore
No. members : 4
No. arrays  : 4
No. groups  : 0
Arrays      : energy, pressure, temperature, velocity

#### Indexing, Compare to 0

In [21]:
print("Checking whether field all zeros - True is bad!")

for t in range(105):
    print("t=", t, " - ", np.all(jhf_hr_zarr['temperature'][t,:64,:64,:64,0] == 0))

Checking whether field all zeros - True is bad!
t= 0  -  False
t= 1  -  False
t= 2  -  False
t= 3  -  False
t= 4  -  False
t= 5  -  True
t= 6  -  True
t= 7  -  True
t= 8  -  True
t= 9  -  True
t= 10  -  True
t= 11  -  True
t= 12  -  True
t= 13  -  True
t= 14  -  True
t= 15  -  True
t= 16  -  True
t= 17  -  True
t= 18  -  True
t= 19  -  True
t= 20  -  True
t= 21  -  True
t= 22  -  True
t= 23  -  True
t= 24  -  True
t= 25  -  True
t= 26  -  True
t= 27  -  True
t= 28  -  True
t= 29  -  True
t= 30  -  True
t= 31  -  True
t= 32  -  True
t= 33  -  True
t= 34  -  True
t= 35  -  True
t= 36  -  True
t= 37  -  True
t= 38  -  True
t= 39  -  True
t= 40  -  True
t= 41  -  True
t= 42  -  True
t= 43  -  True
t= 44  -  True
t= 45  -  True
t= 46  -  True
t= 47  -  True
t= 48  -  True
t= 49  -  True
t= 50  -  True
t= 51  -  True
t= 52  -  True
t= 53  -  True
t= 54  -  True
t= 55  -  True
t= 56  -  True
t= 57  -  True
t= 58  -  True
t= 59  -  True
t= 60  -  True
t= 61  -  True
t= 62  -  True
t= 63  -  Tr

#### Comparing Real Values

In [4]:
jhf_hr_zarr['temperature'][0,:10,0,0,0]

array([-6.5814753, -6.332371 , -6.280685 , -6.27485  , -6.2921414,
       -6.282182 , -6.255372 , -6.216804 , -6.177907 , -6.148448 ],
      dtype=float32)

In [38]:
jhf_lr_zarr['temperature'][0,:10,0,0,0]

array([-6.5814753, -6.332371 , -6.280685 , -6.27485  , -6.2921414,
       -6.282182 , -6.255372 , -6.216804 , -6.177907 , -6.148448 ],
      dtype=float32)

In [7]:
jhf_hr_zarr['temperature'][1,:10,0,0,0]

array([-6.663498 , -6.4969425, -6.4357715, -6.3522453, -6.256171 ,
       -6.214979 , -6.1791387, -6.0816383, -5.8965683, -5.821159 ],
      dtype=float32)

In [27]:
zarr_comparison_data = jhf_hr_zarr['temperature'][0,:10,0,0,0]

for t in range(105):
    raw_t_path = f"/home/idies/workspace/turbulence-ceph-staging/ncar-jhf/hr/jhf.{t:03d}.nc"
    raw_xr = xr.open_dataset(raw_t_path)
    
    print("t: ", t, np.all(zarr_comparison_data == np.array(raw_xr['t'][:10,0,0])))

t:  0 False
t:  1 False
t:  2 False
t:  3 False
t:  4 False
t:  5 False
t:  6 False
t:  7 False
t:  8 False
t:  9 False
t:  10 False
t:  11 False
t:  12 False
t:  13 False
t:  14 False
t:  15 False
t:  16 False
t:  17 False
t:  18 False
t:  19 False
t:  20 False
t:  21 False
t:  22 False
t:  23 False
t:  24 False
t:  25 False
t:  26 False
t:  27 False
t:  28 False
t:  29 False
t:  30 False
t:  31 False
t:  32 False
t:  33 False
t:  34 False
t:  35 False
t:  36 False
t:  37 False
t:  38 False
t:  39 False
t:  40 False
t:  41 False
t:  42 False
t:  43 False
t:  44 False
t:  45 False
t:  46 False
t:  47 False
t:  48 False
t:  49 False
t:  50 False
t:  51 False
t:  52 False
t:  53 False
t:  54 False
t:  55 False
t:  56 False
t:  57 False
t:  58 False
t:  59 False
t:  60 False
t:  61 False
t:  62 False
t:  63 False
t:  64 False
t:  65 False
t:  66 False
t:  67 False
t:  68 False
t:  69 False
t:  70 False
t:  71 False
t:  72 False
t:  73 False
t:  74 False
t:  75 False
t:  76 False
t:  77 Fa

In [28]:
zarr_comparison_data = jhf_hr_zarr['temperature'][0,:10,0,0,0]

for t in range(105):
    raw_t_path = f"/home/idies/workspace/turbulence-ceph-staging/ncar-jhf/hr/jhf.{t:03d}.nc"
    raw_xr = xr.open_dataset(raw_t_path)
    
    print("t: ", t, np.all(zarr_comparison_data == np.array(raw_xr['t'][0,0,:10])))

t:  0 False
t:  1 False
t:  2 False
t:  3 False
t:  4 False
t:  5 False
t:  6 False
t:  7 False
t:  8 False
t:  9 False
t:  10 False
t:  11 False
t:  12 False
t:  13 False
t:  14 False
t:  15 False
t:  16 False
t:  17 False
t:  18 False
t:  19 False
t:  20 False
t:  21 False
t:  22 False
t:  23 False
t:  24 False
t:  25 False
t:  26 False
t:  27 False
t:  28 False
t:  29 False
t:  30 False
t:  31 False
t:  32 False
t:  33 False
t:  34 False
t:  35 False
t:  36 False
t:  37 False
t:  38 False
t:  39 False
t:  40 False
t:  41 False
t:  42 False
t:  43 False
t:  44 False
t:  45 False
t:  46 False
t:  47 False
t:  48 False
t:  49 False
t:  50 False
t:  51 False
t:  52 False
t:  53 False
t:  54 False
t:  55 False
t:  56 False
t:  57 False
t:  58 False
t:  59 False
t:  60 False
t:  61 False
t:  62 False
t:  63 False
t:  64 False
t:  65 False
t:  66 False
t:  67 False
t:  68 False
t:  69 False
t:  70 False
t:  71 False
t:  72 False
t:  73 False
t:  74 False
t:  75 False
t:  76 False
t:  77 Fa

In [24]:
np.array(jhf_hr_netcdf_t104['t'][0,0,:10])

array([-7.189403 , -7.184422 , -7.1883793, -7.2159348, -7.2424674,
       -7.2258234, -7.1829424, -7.1336718, -7.0912566, -7.081466 ],
      dtype=float32)

In [15]:
np.array(jhf_hr_netcdf_t1['t'][0,0,:10])

array([-7.1381   , -7.139076 , -7.142978 , -7.161465 , -7.1812053,
       -7.195337 , -7.2108417, -7.2232113, -7.226865 , -7.229301 ],
      dtype=float32)

In [8]:
np.array(jhf_hr_netcdf_t0['t'][0,0,:10])

array([-7.1410723, -7.131884 , -7.136459 , -7.1370983, -7.149565 ,
       -7.171342 , -7.1852684, -7.196304 , -7.211219 , -7.2230844],
      dtype=float32)

In [12]:
np.array(jhf_hr_netcdf_t0['t'][0,:10,0])

array([-7.1410723, -7.167308 , -7.2093787, -7.230454 , -7.2217207,
       -7.175091 , -7.1131783, -7.1049848, -7.159568 , -7.2159944],
      dtype=float32)

In [6]:
jhf_hr_zarr['temperature'][0,0,0,:10,0]

array([-6.5814753, -6.593374 , -6.6495066, -6.660971 , -6.5991373,
       -6.5511084, -6.5464263, -6.5469503, -6.568524 , -6.6024356],
      dtype=float32)

In [11]:
jhf_hr_zarr['energy'][0,:10,0,0,0]

array([0.01828164, 0.01951831, 0.02175151, 0.0164807 , 0.01907601,
       0.01887238, 0.02590372, 0.03132461, 0.03639093, 0.02927056],
      dtype=float32)

In [10]:
np.array(jhf_hr_netcdf_t0['e'][:10,0,0])

array([0.01936376, 0.01544554, 0.01508535, 0.01503311, 0.01338829,
       0.00952396, 0.00756552, 0.00665405, 0.00746345, 0.00694657],
      dtype=float32)

In [ ]:
# Xarray complains about missing metadata. NOT Fixed by GPT o1
# written_ds_xr = xr.open_dataset(stored_jhf_path, engine='zarr', consolidated=False)

In [20]:
jhf_hr_zarr['energy'].shape

(105, 2048, 2048, 2048, 1)

In [22]:
original_ds.info

NameError: name 'original_ds' is not defined

In [ ]:
ds['velocity'][0, :10,0,0, 0]

In [ ]:
import numpy as np

np.all(ds['velocity'][0, :10,0,0, 0] == 0)

In [ ]:
import numpy as np

np.all(ds['velocity'][100, :10,0,0, 0] == 0)

In [ ]:
import numpy as np

np.all(ds['energy'][100, :10,0,0, 0] == 0)

### Low-Rate

In [33]:
stored_jhf_lr_path = "/home/idies/workspace/turbulence-ceph-staging/sciserver-turbulence/stsabl2048low/stsabl2048low.zarr"
raw_jhf_lr_0_path = "/home/idies/workspace/turbulence-ceph-staging/ncar-jhf/lr/jhf.000.nc"
raw_jhf_lr_1_path = "/home/idies/workspace/turbulence-ceph-staging/ncar-jhf/lr/jhf.001.nc"
raw_jhf_lr_19_path = "/home/idies/workspace/turbulence-ceph-staging/ncar-jhf/lr/jhf.019.nc"

In [34]:
import zarr
import xarray as xr
import numpy as np

jhf_lr_zarr = zarr.open(stored_jhf_lr_path)
jhf_lr_netcdf_t0 = xr.open_dataset(raw_jhf_lr_0_path)
jhf_lr_netcdf_t1 = xr.open_dataset(raw_jhf_lr_1_path)
jhf_lr_netcdf_t19 = xr.open_dataset(raw_jhf_lr_19_path)

#### Comparing Real Values

In [35]:
jhf_lr_zarr['temperature'][0,:10,0,0,0]

array([-6.5814753, -6.332371 , -6.280685 , -6.27485  , -6.2921414,
       -6.282182 , -6.255372 , -6.216804 , -6.177907 , -6.148448 ],
      dtype=float32)

In [37]:
np.array(jhf_lr_netcdf_t0['t'][:10,0,0])

array([-6.5814753, -6.332371 , -6.280685 , -6.27485  , -6.2921414,
       -6.282182 , -6.255372 , -6.216804 , -6.177907 , -6.148448 ],
      dtype=float32)

### Data Statistics

In [ ]:
ds['temperature'].shape

In [ ]:
ds['temperature']

In [ ]:
xy_means = []

for i in range(0, 2048, 50):
    # Remember, nnz-nny-nnx
    xy_means.append(ds['temperature'][0,i,:,:,0].mean())
    

from matplotlib import pyplot as plt

plt.plot(list(range(0, ds['temperature'].shape[1], 50)), xy_means)

plt.title("Mean Temperature across Z")
plt.xlabel("Slice (Z)")
plt.ylabel("Average Temperature")

In [ ]:
from matplotlib import pyplot as plt


xy_means_original = []

for i in range(0, 2048, 50):
    xy_means_original.append(original_ds['t'][i,:,:].mean())

plt.plot(list(range(0, ds['temperature'].shape[1], 50)), xy_means_original)

plt.title("Temperature across Z")
plt.xlabel("Slice (Z)")
plt.ylabel("Average Temperature")

In [ ]:
yz_means = []


for i in range(0, 2048, 50):
    yz_means.append(ds['temperature'][0,:,:,i,0].mean())


plt.plot(list(range(0, 2048, 50)), yz_means)
plt.title("Temperature across X")
plt.xlabel("Slice (X)")
plt.ylabel("Average Temperature")

In [ ]:
yz_means_original = []

for i in range(0, 2048, 50):
    yz_means_original.append(original_ds['t'][:,:,i].mean())


plt.plot(list(range(0, 2048, 50)), yz_means_original)
plt.title("Temperature across X")
plt.xlabel("Slice (X)")
plt.ylabel("Average Temperature")

### Slice Plotting

This can take a few minutes

### Sciserver doesn't allow localhost connections, so can't use Dask Cluster console

In [ ]:
import zarr
import dask.array as da
import matplotlib.pyplot as plt
from dask import compute
from dask.diagnostics import ProgressBar

# Open the Zarr group
store = zarr.open_group(stored_jhf_path, mode='r')

# Create Dask arrays
data_arrays = {}
variables = list(store.array_keys())
for var_name in variables:
    zarr_array = store[var_name]
    dask_array = da.from_zarr(zarr_array)
    # Squeeze scalar variables
    if dask_array.shape[-1] == 1:
        dask_array = dask_array.squeeze(axis=-1)
    data_arrays[var_name] = dask_array

# Function to collect data slices
def collect_data_slices(data_arrays, variables, timesteps):
    data_slices = []
    titles = []
    for variable in variables:
        for timestep in timesteps:
            dask_array = data_arrays[variable]
            
            # Get slices along each dimension
            x_slice = dask_array[timestep, :, :, 0]
            y_slice = dask_array[timestep, :, 0, :]
            z_slice = dask_array[timestep, 0, :, :]
            
            # For vector variables, handle components
            if variable == 'velocity':
                for component in range(3):
                    x_comp_slice = x_slice[..., component]
                    y_comp_slice = y_slice[..., component]
                    z_comp_slice = z_slice[..., component]
                    
                    data_slices.extend([x_comp_slice, y_comp_slice, z_comp_slice])
                    titles.extend([
                        f"{variable} (component {component}) nnx=0 Timestep={timestep}",
                        f"{variable} (component {component}) nny=0 Timestep={timestep}",
                        f"{variable} (component {component}) nnz=0 Timestep={timestep}"
                    ])
            else:
                data_slices.extend([x_slice, y_slice, z_slice])
                titles.extend([
                    f"{variable} nnx=0 Timestep={timestep}",
                    f"{variable} nny=0 Timestep={timestep}",
                    f"{variable} nnz=0 Timestep={timestep}"
                ])
    return data_slices, titles

# Variables and timesteps
variables = ['energy', 'temperature', 'pressure', 'velocity']
timesteps = range(0, data_arrays['energy'].shape[0], 5)  # Every 5th timestep

# Collect data slices
data_slices, titles = collect_data_slices(data_arrays, variables, timesteps)

# Compute all data slices at once
with ProgressBar():
    computed_slices = compute(*data_slices)

# Plot all images
for data, title in zip(computed_slices, titles):
    plt.figure()
    plt.imshow(data)
    plt.title(title)
    plt.gca().invert_yaxis()
    plt.colorbar()
    plt.show()


In [ ]:
from matplotlib import pyplot as plt

def plot_along_3_dimensions(ds, variable, plot_component=0, timestep = 0):
    plt.figure()
    plt.imshow(ds[variable][timestep,:,:, 0, plot_component])
    plt.title(variable + " X=1 + Timestep = " + str(timestep))
    plt.gca().invert_yaxis()
    plt.colorbar()
    
    
    plt.figure()
    plt.imshow(ds[variable][timestep,:,0, :, plot_component])
    plt.title(variable + " Y=1 + Timestep = " + str(timestep))
    plt.gca().invert_yaxis()
    plt.colorbar()

    
    plt.figure()
    plt.imshow(ds[variable][timestep,0,:, :, plot_component])
    plt.title(variable + " Z=1 + Timestep = " + str(timestep))
    plt.gca().invert_yaxis()
    plt.colorbar()

In [ ]:
plt.rcParams['image.cmap'] = 'inferno'

### Checking if write has finished - timestep 19

In [ ]:
ds = ds_zarr

In [ ]:
ds['energy'].info

In [ ]:
ds['energy'][15,:-10,0,0, 0]

In [ ]:
variable = "energy"
timestep = 0

In [ ]:
plot_along_3_dimensions(ds, variable, plot_component=0, timestep = timestep)

In [ ]:
plot_along_3_dimensions(ds, variable="pressure", plot_component=0, timestep = timestep)

In [ ]:
plot_along_3_dimensions(ds, variable="temperature", plot_component=0, timestep = timestep)

In [ ]:
plot_along_3_dimensions(ds, variable="velocity", plot_component=0, timestep = timestep)

In [ ]:
plot_along_3_dimensions(ds, variable="velocity", plot_component=1, timestep = timestep)

In [ ]:
plot_along_3_dimensions(ds, variable="velocity", plot_component=2, timestep = timestep)

In [ ]:
timestep = 1

In [ ]:
plot_along_3_dimensions(ds, variable='energy', plot_component=0, timestep = timestep)

In [ ]:
plot_along_3_dimensions(ds, variable="pressure", plot_component=0, timestep = timestep)

In [ ]:
plot_along_3_dimensions(ds, variable="temperature", plot_component=0, timestep = timestep)

In [ ]:
plot_along_3_dimensions(ds, variable="velocity", plot_component=0, timestep = timestep)

In [ ]:
plot_along_3_dimensions(ds, variable="velocity", plot_component=1, timestep = timestep)

In [ ]:
plot_along_3_dimensions(ds, variable="velocity", plot_component=2, timestep = timestep)

In [ ]:
import dask.array as da

In [ ]:
da.equal(ds['energy'][0,:,:, 0, 0], original_ds['e'][:,:,0])

In [ ]:
from matplotlib import pyplot as plt

plt.imshow(ds['energy'][0,:,0, :, 0])
plt.title("Y=1")
plt.gca().invert_yaxis()
plt.colorbar()

In [ ]:
plt.imshow(ds['energy'][0,0,:, :, 0])
plt.title("Z=1")
plt.gca().invert_yaxis()
plt.colorbar()

In [ ]:
plot_along_3_dimensions(ds, 'pressure')

In [ ]:
plot_along_3_dimensions(ds, 'temperature')

In [ ]:
# Original data
plt.imshow(original_ds['t'][:, :, 0], cmap="inferno")
plt.gca().invert_yaxis()  # Invert the y-axis to place 0 at the bottom

plt.title("Temperature at t=1, Low-rate, X=1")
# plt.xlabel("X")
# plt.ylabel("Y")

plt.colorbar()
plt.show()

In [ ]:
# Original data
plt.imshow(original_ds['t'][:, 0, :], cmap="inferno")
plt.gca().invert_yaxis()  # Invert the y-axis to place 0 at the bottom

plt.title("Temperature at t=1, Low-rate, Y=1")
plt.xlabel("X")
plt.ylabel("Z")

plt.colorbar()
plt.show()

## Velocity u

In [ ]:
plot_along_3_dimensions(ds, 'velocity', 0)

In [ ]:
# Original data
plt.imshow(original_ds['u'][0, :, :], cmap="inferno")
plt.gca().invert_yaxis()  # Invert the y-axis to place 0 at the bottom

plt.title("u at t=1, Low-rate, Z=1")
plt.xlabel("X")
plt.ylabel("Y")

plt.colorbar()
plt.show()

In [ ]:
# Original data
plt.imshow(original_ds['u'][:, :, 0], cmap="inferno")
plt.gca().invert_yaxis()  # Invert the y-axis to place 0 at the bottom

plt.title("u at t=1, Low-rate, X=1")
plt.xlabel("X")
plt.ylabel("Y")

plt.colorbar()
plt.show()

In [ ]:
# Original data
plt.imshow(original_ds['u'][:, 0, :], cmap="inferno")
plt.gca().invert_yaxis()  # Invert the y-axis to place 0 at the bottom

plt.title("u at t=1, Low-rate, Y=1")
plt.xlabel("X")
plt.ylabel("Y")

plt.colorbar()
plt.show()

## Velocity v

In [ ]:
plot_along_3_dimensions(ds, 'velocity', 1)

## Velocity w

In [ ]:
plot_along_3_dimensions(ds, 'velocity', 2)